### ISSUE TITLE
it works now

### ISSUE THREAD

**Issue by notedit** [notedit/rtprecorder#1]
i still use the ffmpeg command.  i just have a test, it can works now.

you can give me some feedback.

@zacharynevin

**Comment by hailiang-wang** [comment]
怎么玩？

```
npm install
node example/testRecroder.js
```

并没有看到输出什么

**Comment by notedit** [comment]
这个库的目的是录制rtp 数据.

测试代码的流程是这样的:

1,根据预设的音视频信息(codes) 生成sdp 以及初始化audio 和 video的udp port. 

2,然后用ffmpeg模拟rtp流,  根据第一步得到的audio video port 发送 音视频的rtp包.

3,然后用stream.startRecording 开始录制上面产生的两路rtp流.  保存成一个视频.

需要在服务端跟webrtc配合用, 我们要用到的一个组件.  

DEBUG=*  node example/testRecroder.js 能看到打印信息.

**Comment by debug6699** [comment]
把rtp 数据输出到文件，然后再把文件转录成mp4 是否可行？

**Comment by notedit** [comment]
需要做些编码  你可以参考我的ffmpeg命令

**Comment by debug6699** [comment]
多谢，我研究一下，这样可以避开服务器使用高峰期

**Comment by notedit** [comment]
不需要啊   我的这个库支持网络rtp发送  自己写个server 集成一下就可以
