### ISSUE TITLE
Mediasoup example?

### ISSUE THREAD

**Issue by tmehlinger** [notedit/rtprecorder#4]
Hi! I saw your message from December on the Mediasoup mailing list and thought you could provide some insight.

Do you have or could you point me to an example using this with a Mediasoup-enabled server? From your post on the mailing list, I gathered you had made this work with the RTP stream coming from Mediasoup's `RtpStreamer` but I haven't had much luck making this work myself.

Thanks!

**Comment by zacharynevin** [comment]
In mediasoup v2.0 you can create an RTP mirror. My suggestion would be to mirror your RTP packets to a server running [gstreamer](https://gstreamer.freedesktop.org/). 

In gstreamer you can write your media processing pipeline as a graph in C++. There is an official plugin for ingesting RTP packets over UDP.

**Comment by tmehlinger** [comment]
I'll look into it, thanks!
