### ISSUE TITLE
Is the maintainer still active?

### ISSUE THREAD

**Issue by isaacnass** [notedit/rtprecorder#7]
Hi there!

First of all - thanks for the _killer_ package! Building something like this on ffmpeg is the right way to go (seeing as most video sources are most likely coming from there), it just makes sense in regards to tech uniformity.

I made some changes on my end, mainly around time-based segmentation. I'm not too much of a wizard with ffmpeg so if you're around to shed some light I'd be happy to clean them up and open a PR! I opened another PR which wasn't merged so I just wanted to see if you're around.

Also I wanted to see if there was anything that could be done regarding multiple streams (i.e. sink all my audio sources into one recorder), as well as video starting at a different time than the audio (potentially using nullsrc when video is enabled but audio is not there)

Thanks a lot!

**Comment by notedit** [comment]
yes,  we still use this lib in our product.  

i made  some code change these days  and have not test it yet.  

i will continue do some work  next month.    i think your problom is doable,  but maybe need use some ffmpeg api do to that.
